### ISSUE TITLE
Please update version on Rubygems

### ISSUE THREAD

**Issue by CVTJNII** [flapjack/flapjack-diner#55]
The published gem on Rubygems is 1.3.0 from March 19th, which doesn't have important patches added since then, namely d691742..  Can you please bump patch and push a new release?

**Comment by ali-graham** [comment]
I'll do it later today.

**Comment by ali-graham** [comment]
https://rubygems.org/gems/flapjack-diner/versions/1.4.0

**Comment by CVTJNII** [comment]
Thanks!
